### PR TITLE
Fix issues with references in API ref

### LINKED ISSUE #367: API Ref: Missing words in class descriptions
In a couple of places in the toolkit API reference, there are missing words in the class descriptions. It looks like perhaps variables that are not rendering an expected value (see also refs?).

For example: 
- [SymbolDisplay](https://esri.github.io/arcgis-toolkit-dotnet/api/android/Esri.ArcGISRuntime.Toolkit.UI.Controls.SymbolDisplay.html): "A control that renders a ."
- [PopupViewer](https://esri.github.io/arcgis-toolkit-dotnet/api/android/Esri.ArcGISRuntime.Toolkit.UI.Controls.PopupViewer.html): "The PopupViewer control is used to display details and media, edit attributes, geometry and related records, manage attachments of an or a as defined in its ."
- [Legend](https://esri.github.io/arcgis-toolkit-dotnet/api/android/Esri.ArcGISRuntime.Toolkit.UI.Controls.Legend.html): "The Legend control is used to display symbology and description for a set of s in a or contained in a GeoView."

### PR DESCRIPTION
**Pull request by nCastle1**
Resolves #367

### CODE REVIEW

**Review by dotMorten — CHANGES_REQUESTED** [review]
This shouldn't be fixed in doc. This needs to be fixed in the docfx build by having it point the xref maps that we generate.
ie
- https://developers.arcgis.com/net/api-reference/netstandard.xrefmap.yml
- https://developers.arcgis.com/net/api-reference/net.xrefmap.yml
- https://developers.arcgis.com/net/api-reference/netstandard.xrefmap.yml
- https://developers.arcgis.com/net/api-reference/android.xrefmap.yml
- https://developers.arcgis.com/net/api-reference/ios.xrefmap.yml 
- https://developers.arcgis.com/net/api-reference/uwp.xrefmap.yml
- https://developers.arcgis.com/net/api-reference/netwin.xrefmap.yml
- https://developers.arcgis.com/net/api-reference/netfx.xrefmap.yml
- https://developers.arcgis.com/net/api-reference/xrefmap.yml

See https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#using-cross-reference-map

**Comment by pMaske** [comment]
may be @ThadT can guide?

**Comment by dotMorten** [comment]
Likely just need to add `https://developers.arcgis.com/net/api-reference/netstandard.xrefmap.yml` to https://github.com/Esri/arcgis-toolkit-dotnet/blob/1050fd8c2dbcead6252e26e47ddcc6e962513259/docs/docfx.json#L161

**Comment by ThadT** [comment]
Yeah, I think @dotMorten suggestion is the way to go. It would be easy to test.

**Pull request closed without merging**
