### PR TITLE
Add MAUI support

### PR DESCRIPTION
**Pull request by espenrl**
Hi, I've started initial support for MAUI. So far I've created `Esri.ArcGISRuntime.Toolkit.Maui` and `Toolkit.Samples.Maui` with a rough implementation of `Compass` and `ScaleLine` for demonstration. Getting the build process to work has been the first major struggle to handle.

There is still lots to do. WinUI support, all controls with samples. Before I continue on those features I first want to get into a discussion if this is a viable route to go, or if ESRI already is doing their own implementation.

### CODE REVIEW

**Comment by espenrl** [comment]
@dotMorten

**Comment by dotMorten** [comment]
@espenrl Hey Espen. Thank you for all this work. We do have adding MAUI support on our list in the next few months, but unfortunately we're planning to do some major shuffling and rearchitecture of the entire project system (to reduce some of the build process issues you also hit), before doing that, so it's a little hard for us to accept the PR as is. I'll leave it open here for now though, in case people are looking for a maui port today.

**Comment by espenrl** [comment]
I've actually managed to get WinUI fully working and mapping to MAUI. I'm willing to complete all the controls for MAUI and make sample apps for both WinUI (native) and MAUI.

If ESRI is willing to accept this PR upon completion I will continue, otherwise I won't of course waste time. Forms will have to be removed after the PR.

**Comment by dotMorten** [comment]
@espenrl Thanks. I appreciate the offer, but as we're moving towards v200 with full MAUI and WinUI support, we're going to have to do some major refactoring to the entire toolkit build system. There's also quite a lot of work still ongoing for Forms for v100.15, and we'd like to get all that work complete, before starting a full Maui port.

**Comment by espenrl** [comment]
I understand. Well, I pushed the commit with support for WinUI. It breaks WPF for .NET 5, but I won't do anything about that. For the project I'm working on the targets are MAUI with Android, iOS and WinUI. And I have got that working and I'm satisfied now. Still waiting for MAUI Service Release 3 to fix the Android build issue.

**Comment by dotMorten** [comment]
>  It breaks WPF for .NET 5, 

That's one of the main reasons we need to do a major refactor.

**Comment by dotMorten** [comment]
We've started the work to rearchitect the project structure for the next major release.  For now that branch builds against v100.15, so you could try that out.  See the v200 branch: https://github.com/Esri/arcgis-toolkit-dotnet/tree/v200
It's still a work in progress, and some of the maui controls are actively being ported, but WPF, WinUI and UWP should be pretty much good to go, and most of the MAUI ones as well.
I'm going to close this branch in favor or the restructure work.

**Comment by espenrl** [comment]
Thank you for the update Morten. It's exiting times with MAUI progressing nicely, and AGR v200 on the horizon.

**Pull request closed without merging**
